name: Publish site to Github Pages
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set Github credentials
        env:
          MY_EMAIL: louiscmancini@@gmail.com
          MY_NAME: louism2
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.PASSWORD }}@github.com/your_name/your_repository.git
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Publish site to Github Pages
        run: npm run deploy
