name: Publish site to Github Pages
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Publish site to Github Pages
        run: npm run deploy
